variable "name" {
  description = "Short, stable prefix for the remote development resources."
  type        = string
  default     = "compass-dev"
}

variable "location" {
  description = "Azure region for the remote development VM."
  type        = string
  default     = "westus2"
}

variable "resource_group_name" {
  description = "Optional resource group override. Defaults to <name>-rg."
  type        = string
  default     = ""
}

variable "vm_size" {
  description = "VM size for Docker, OpenSearch, Neo4j, Qdrant, and app containers."
  type        = string
  default     = "Standard_D8as_v5"
}

variable "os_disk_size_gb" {
  description = "OS disk size for source, Docker images, and local volumes."
  type        = number
  default     = 256
}

variable "admin_username" {
  description = "Linux administrator created with SSH-key-only access."
  type        = string
  default     = "devuser"
}

variable "ssh_public_key" {
  description = "Public SSH key generated by scripts/azure_dev.sh."
  type        = string
}

variable "ssh_source_cidr" {
  description = "CIDR allowed to reach SSH. The lifecycle script detects the current public IP."
  type        = string
}

variable "vnet_cidr" {
  description = "Private address space for the remote development VNet."
  type        = string
  default     = "10.42.0.0/16"
}

variable "subnet_cidr" {
  description = "Subnet address space for the remote development VM."
  type        = string
  default     = "10.42.1.0/24"
}

variable "auto_shutdown_enabled" {
  description = "Automatically deallocate the VM every day to avoid idle compute charges."
  type        = bool
  default     = true
}

variable "auto_shutdown_time_utc" {
  description = "Daily VM auto-shutdown time in HHmm UTC."
  type        = string
  default     = "2300"
}

variable "tags" {
  description = "Tags applied to remote development resources."
  type        = map(string)
  default = {
    Project = "Compass"
    Owner   = "engineering"
  }
}
